# Generated by Django 5.2.17 on 2026-09-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('invoice_date', models.DateField()),
                ('payment_terms', models.TextField(blank=True)),
                ('delivery_terms', models.TextField(blank=True)),
                ('project_notes', models.TextField(blank=True)),
                ('loading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('freight_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='crm.staff')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='crm.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='crm.vendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=40)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='Unit', max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.purchaseinvoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status'], name='crm_purchas_status_3c19b8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['vendor'], name='crm_purchas_vendor__cfcfe0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_date'], name='crm_purchas_invoice_5c2998_idx'),
        ),
    ]
