# Generated by Django 5.2.17 on 2026-09-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_purchaseinvoice_purchaseinvoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('installation', 'Installation'), ('service', 'Service'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('follow_up', 'Follow Up'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activities', to='crm.staff')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activities', to='crm.customer')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activities', to='crm.enquiry')),
            ],
            options={
                'ordering': ('status', 'due_date', '-created_at'),
                'indexes': [models.Index(fields=['status'], name='crm_jobacti_status_740f44_idx'), models.Index(fields=['priority'], name='crm_jobacti_priorit_250a2f_idx'), models.Index(fields=['start_date'], name='crm_jobacti_start_d_615c47_idx'), models.Index(fields=['due_date'], name='crm_jobacti_due_dat_31102f_idx')],
            },
        ),
    ]
