# Generated by Django 5.2.17 on 2026-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_jobactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_job_activities', to='crm.staff'),
        ),
        migrations.AddField(
            model_name='jobactivity',
            name='repeat_every',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
