# Generated by Django 5.2.17 on 2026-09-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_jobactivity_billable_jobactivity_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['name'], name='crm_referra_name_06f21b_idx'), models.Index(fields=['company'], name='crm_referra_company_0cad7d_idx'), models.Index(fields=['city'], name='crm_referra_city_3a04a1_idx')],
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='referral_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='crm.referralpartner'),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.referralpartner'),
        ),
    ]
