# Generated by Django 5.2.17 on 2026-09-16 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_referralpartner_enquiry_referral_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('supply', 'Supply'), ('installation', 'Installation'), ('service', 'Service'), ('completed', 'Completed')], default='supply', max_length=30)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('billing_type', models.CharField(choices=[('fixed_rate', 'Fixed Rate'), ('hourly', 'Hourly')], default='fixed_rate', max_length=20)),
                ('total_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='in_progress', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('visible_tabs', models.JSONField(blank=True, default=list)),
                ('customer_can_view_job_activities', models.BooleanField(default=True)),
                ('customer_can_create_job_activities', models.BooleanField(default=True)),
                ('customer_can_edit_job_activities', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.staff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='crm_project_status_9d26bc_idx'), models.Index(fields=['stage'], name='crm_project_stage_a94f92_idx'), models.Index(fields=['start_date'], name='crm_project_start_d_76f374_idx')],
            },
        ),
    ]
