# Generated by Django 5.2.17 on 2026-09-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activities', to='crm.project'),
        ),
    ]
