# Generated by Django 5.2.17 on 2026-09-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_jobactivity_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('amc_type', models.CharField(blank=True, max_length=120)),
                ('amc_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('about_to_expire', 'About to Expire'), ('recently_added', 'Recently Added'), ('trash', 'Trash')], default='active', max_length=30)),
                ('is_trashed', models.BooleanField(default=False)),
                ('signature_status', models.CharField(default='not_signed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amc_contracts', to='crm.customer')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='crm_amccont_status_018b2e_idx'), models.Index(fields=['amc_type'], name='crm_amccont_amc_typ_6f4612_idx'), models.Index(fields=['start_date'], name='crm_amccont_start_d_bd219a_idx'), models.Index(fields=['end_date'], name='crm_amccont_end_dat_c990fb_idx')],
            },
        ),
    ]
