# Generated by Django 5.2.17 on 2026-09-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_amccontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='hide_from_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_contracts', to='crm.project'),
        ),
    ]
