# Generated by Django 5.2.17 on 2026-09-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_amccontract_hide_from_customer_amccontract_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('cc', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('answered', 'Answered'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='open', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='crm.staff')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='crm.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='crm.customer')),
                ('job_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='crm.jobactivity')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='crm_complai_status_9d0433_idx'), models.Index(fields=['priority'], name='crm_complai_priorit_4cc83b_idx'), models.Index(fields=['created_at'], name='crm_complai_created_763184_idx')],
            },
        ),
    ]
