# Generated by Django 5.2.17 on 2026-09-17 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_proformainvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstinvoice',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='client_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_invoices', to='crm.project'),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='reference_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='sales_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_invoices', to='crm.staff'),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GSTInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.gstinvoice')),
            ],
        ),
    ]
