# Generated by Django 5.2.17 on 2026-09-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_gstinvoice_adjustment_gstinvoice_client_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
