# Generated by Django 5.2.17 on 2026-09-17 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_advancepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('credit_note_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('discount_type', models.CharField(default='none', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('admin_note', models.TextField(blank=True)),
                ('client_note', models.TextField(blank=True)),
                ('declaration', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='crm.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=40)),
                ('nos', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.creditnote')),
            ],
        ),
    ]
