# Generated by Django 5.2.17 on 2026-09-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_creditnote_creditnoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=40)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='Unit', max_length=40)),
                ('item_type', models.CharField(default='Service', max_length=40)),
                ('purchase_unit', models.CharField(default='Unit', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='crm.itemgroup')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='crm_item_name_56b43a_idx'), models.Index(fields=['sku'], name='crm_item_sku_43e82d_idx')],
            },
        ),
    ]
