# Generated by Django 5.2.17 on 2026-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_itemgroup_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
