# Generated by Django 5.2.17 on 2026-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
    ]
