# Generated by Django 5.2.17 on 2026-09-17 10:19

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_amctype_campaign_complaintdepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackup',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('D:/Sajo Projects/Sajo CCTV CRM/backend/private_backups')), upload_to=''),
        ),
    ]
