# Generated by Django 5.2.17 on 2026-09-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_alter_databasebackup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
