from rest_framework.routers import DefaultRouter
from django.urls import include, path

from .views import AMCContractViewSet, AMCTypeViewSet, ActivityLogViewSet, AdvancePaymentViewSet, CalendarEventViewSet, CampaignViewSet, ComplaintDepartmentViewSet, ComplaintPriorityViewSet, ComplaintViewSet, ContactViewSet, CreditNoteViewSet, CurrencyViewSet, CustomerGroupViewSet, CustomerViewSet, DashboardView, DatabaseBackupViewSet, EmailIntegrationViewSet, EmailTemplateViewSet, EnquiryViewSet, ExpenseCategoryViewSet, ExpenseViewSet, GSTInvoiceViewSet, GoalViewSet, ItemGroupViewSet, ItemViewSet, JobActivityChecklistViewSet, JobActivityTemplateViewSet, JobActivityViewSet, LeadHotnessLevelViewSet, LeadReasonViewSet, LeadSourceViewSet, LeadStatusViewSet, LeadViewSet, MenuEntryViewSet, PaymentModeViewSet, PaymentViewSet, PredefinedReplyViewSet, ProformaInvoiceViewSet, ProjectViewSet, PurchaseInvoiceViewSet, PurchaseOrderViewSet, QuotationViewSet, ReferralPartnerViewSet, RoleViewSet, SettingViewSet, StaffDesignationViewSet, StaffViewSet, TaxRateViewSet, ThemeStyleViewSet, TodoViewSet, UnitViewSet, VendorViewSet, WebToLeadFormViewSet

router = DefaultRouter()
router.register("customers", CustomerViewSet)
router.register("referral-partners", ReferralPartnerViewSet)
router.register("projects", ProjectViewSet)
router.register("amc-contracts", AMCContractViewSet)
router.register("complaints", ComplaintViewSet)
router.register("contacts", ContactViewSet)
router.register("leads", LeadViewSet)
router.register("enquiries", EnquiryViewSet)
router.register("staff", StaffViewSet)
router.register("vendors", VendorViewSet)
router.register("purchase-orders", PurchaseOrderViewSet)
router.register("purchase-invoices", PurchaseInvoiceViewSet)
router.register("calendar-events", CalendarEventViewSet)
router.register("todos", TodoViewSet)
router.register("job-activities", JobActivityViewSet)
router.register("quotations", QuotationViewSet)
router.register("proforma-invoices", ProformaInvoiceViewSet)
router.register("gst-invoices", GSTInvoiceViewSet)
router.register("payments", PaymentViewSet)
router.register("advance-payments", AdvancePaymentViewSet)
router.register("credit-notes", CreditNoteViewSet)
router.register("item-groups", ItemGroupViewSet)
router.register("items", ItemViewSet)
router.register("expense-categories", ExpenseCategoryViewSet)
router.register("expenses", ExpenseViewSet)
router.register("activity-logs", ActivityLogViewSet, basename="activity-log")
router.register("goals", GoalViewSet)
router.register("database-backups", DatabaseBackupViewSet, basename="database-backup")
router.register("customer-groups", CustomerGroupViewSet)
router.register("staff-designations", StaffDesignationViewSet)
router.register("complaint-departments", ComplaintDepartmentViewSet)
router.register("predefined-replies", PredefinedReplyViewSet)
router.register("complaint-priorities", ComplaintPriorityViewSet)
router.register("priorities", ComplaintPriorityViewSet, basename="priority")
router.register("job-activity-templates", JobActivityTemplateViewSet)
router.register("job-activity-checklists", JobActivityChecklistViewSet)
router.register("lead-sources", LeadSourceViewSet)
router.register("lead-statuses", LeadStatusViewSet)
router.register("lead-hotness-levels", LeadHotnessLevelViewSet)
router.register("lead-heatness-levels", LeadHotnessLevelViewSet, basename="lead-heatness-level")
router.register("campaigns", CampaignViewSet)
router.register("email-integrations", EmailIntegrationViewSet)
router.register("web-to-lead-forms", WebToLeadFormViewSet)
router.register("lead-reasons", LeadReasonViewSet)
router.register("reasons", LeadReasonViewSet, basename="reason")
router.register("tax-rates", TaxRateViewSet)
router.register("currencies", CurrencyViewSet)
router.register("payment-modes", PaymentModeViewSet)
router.register("units", UnitViewSet)
router.register("amc-types", AMCTypeViewSet)
router.register("email-templates", EmailTemplateViewSet)
router.register("roles", RoleViewSet)
router.register("main-menu", MenuEntryViewSet, basename="main-menu")
router.register("setup-menu", MenuEntryViewSet, basename="setup-menu")
router.register("menu-entries", MenuEntryViewSet)
router.register("theme-styles", ThemeStyleViewSet)
router.register("settings", SettingViewSet)

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("", include(router.urls)),
]
