import { useEffect, useMemo, useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import api from "../api";

const unwrap = (response) => response.data.results || response.data;
const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

export default function ExpensesReportPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const detailed = location.pathname.endsWith("/detailed");
  const [expenses, setExpenses] = useState([]);
  const [categories, setCategories] = useState([]);
  const [year, setYear] = useState(String(new Date().getFullYear()));
  const [billable, setBillable] = useState(false);
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [search, setSearch] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.get("/expenses/"), api.get("/expense-categories/")]).then(([expenseResponse, categoryResponse]) => { setExpenses(unwrap(expenseResponse)); setCategories(unwrap(categoryResponse)); }).catch(() => setError("Unable to load expense report.")); }, []);
  const filtered = useMemo(() => expenses.filter((expense) => (!fromDate || expense.expense_date >= fromDate) && (!toDate || expense.expense_date <= toDate) && (!search || `${expense.name} ${expense.category_name} ${expense.reference}`.toLowerCase().includes(search.toLowerCase()))), [expenses, fromDate, toDate, search]);
  const visibleExpenses = billable ? filtered.filter((expense) => !expense.billable) : filtered;
  const rows = categories.map((category) => ({ category, values: monthNames.map((_, month) => visibleExpenses.filter((expense) => !expense.billable && expense.category === category.id && expense.expense_date?.startsWith(`${year}-${String(month + 1).padStart(2, "0")}`)).reduce((sum, expense) => sum + Number(expense.amount || 0), 0)), billableValues: monthNames.map((_, month) => filtered.filter((expense) => expense.billable && expense.category === category.id && expense.expense_date?.startsWith(`${year}-${String(month + 1).padStart(2, "0")}`)).reduce((sum, expense) => sum + Number(expense.amount || 0), 0)) }));
  const format = (value) => `₹${value.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
  if (detailed) return <section className="expense-report-detail"><div className="panel report-back"><button className="secondary-button" onClick={() => navigate("/reports/expenses")}>GO BACK</button></div><div className="panel detailed-expense-panel"><div className="date-range"><label>From Date<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>To Date<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label></div><div className="referral-toolbar"><div className="staff-list-controls"><select><option>25</option><option>50</option></select><button className="toolbar-icon-button">EXPORT</button><button className="toolbar-icon-button">↻</button></div><label className="staff-search">⌕ <input placeholder="Search..." value={search} onChange={(event) => setSearch(event.target.value)} /></label></div><table><thead><tr><th>Category</th><th>Amount</th><th>Name</th><th>Tax</th><th>Tax 2</th><th>Total Tax</th><th>Amount with tax</th><th>Billable</th><th>Date</th><th>Customer</th><th>Reference #</th><th>Payment Mode</th></tr></thead><tbody>{filtered.length ? filtered.map((expense) => <tr key={expense.id}><td>{expense.category_name}</td><td>{format(Number(expense.amount || 0))}</td><td>{expense.name}</td><td>{expense.tax}%</td><td>{expense.tax_two}%</td><td>{format(Number(expense.amount || 0) * (Number(expense.tax || 0) + Number(expense.tax_two || 0)) / 100)}</td><td>{format(Number(expense.amount || 0) * (1 + (Number(expense.tax || 0) + Number(expense.tax_two || 0)) / 100))}</td><td>—</td><td>{expense.expense_date}</td><td>{expense.customer_name || "—"}</td><td>{expense.reference || "—"}</td><td>{expense.payment_mode || "—"}</td></tr>) : <tr><td colSpan="12" className="report-empty">No entries found<div className="empty-upload-icon">↥</div></td></tr>}</tbody></table></div></section>;
  const totals = monthNames.map((_, month) => rows.reduce((sum, row) => sum + row.values[month], 0));
  return <section className="expenses-report-page"><div className="panel expenses-report-toolbar"><div><button className="toolbar-icon-button">▣</button><button className="toolbar-icon-button">⇩</button></div><button className="primary-button" onClick={() => navigate("/reports/expenses/detailed")}>DETAILED REPORT</button></div>{error && <p className="error-message">{error}</p>}<div className="panel expense-summary-panel"><label className="checkbox-label"><input type="checkbox" checked={billable} onChange={(event) => setBillable(event.target.checked)} /> Exclude Billable Expenses</label><label className="report-year">Year<select value={year} onChange={(event) => setYear(event.target.value)}><option>{new Date().getFullYear()}</option><option>{new Date().getFullYear() - 1}</option></select></label><table><thead><tr><th>Category</th>{monthNames.map((month) => <th key={month}>{month}</th>)}<th>Year ({year})</th></tr></thead><tbody>{rows.map((row) => <tr key={row.category.id}><td>{row.category.name}</td>{row.values.map((value, index) => <td key={index}>{format(value)}</td>)}<td>{format(row.values.reduce((sum, value) => sum + value, 0))}</td></tr>)}<tr className="expense-total-row"><td>Net Amount (Subtotal)</td>{totals.map((value, index) => <td key={index}>{format(value)}</td>)}<td>{format(totals.reduce((sum, value) => sum + value, 0))}</td></tr><tr className="expense-total-row"><td>Total Tax</td>{totals.map((_, index) => <td key={index}>{format(0)}</td>)}<td>{format(0)}</td></tr><tr className="expense-total-row"><td>Total</td>{totals.map((value, index) => <td key={index}>{format(value)}</td>)}<td>{format(totals.reduce((sum, value) => sum + value, 0))}</td></tr></tbody></table><div className="expense-report-charts"><div><h3>Not billable expenses by categories</h3><div className="mini-expense-chart">{rows.map((row) => <span key={row.category.id} style={{ height: `${Math.max(1, row.values.reduce((a, b) => a + b, 0) / Math.max(...totals, 1) * 100)}%` }} title={row.category.name} />)}</div></div><div><h3>Billable expenses by categories</h3><div className="mini-expense-chart billable-chart">{rows.map((row) => <span key={row.category.id} style={{ height: `${Math.max(1, row.billableValues.reduce((a, b) => a + b, 0) / Math.max(...rows.flatMap((entry) => entry.billableValues), 1) * 100)}%` }} title={row.category.name} />)}</div></div></div></div></section>;
}
