import { useEffect, useState } from "react";
import api from "../api";

const today = new Date().toISOString().slice(0, 10);
const empty = { subject: "", goal_type: "", staff: "", achievement: "", start_date: today, end_date: "", description: "", notify_on_achievement: true, notify_on_failed: true, progress: 0 };
const unwrap = (response) => response.data.results || response.data;

export default function GoalsPage() {
  const [goals, setGoals] = useState([]);
  const [staff, setStaff] = useState([]);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState(empty);
  const [error, setError] = useState("");
  function load() { const query = search ? `?search=${encodeURIComponent(search)}` : ""; Promise.all([api.get(`/goals/${query}`), api.get("/staff/")]).then(([goalResponse, staffResponse]) => { setGoals(unwrap(goalResponse)); setStaff(unwrap(staffResponse)); }).catch(() => setError("Unable to load goals.")); }
  useEffect(() => { load(); }, [search]);
  function update(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event) { event.preventDefault(); try { await api.post("/goals/", form); setEditing(false); setForm(empty); load(); } catch { setError("The goal could not be saved."); } }
  async function remove(goal) { if (!window.confirm(`Delete ${goal.subject}?`)) return; await api.delete(`/goals/${goal.id}/`); load(); }
  if (editing) return <main className="goal-editor"><form className="panel goal-form" onSubmit={save}><h2>Add new goal</h2><label className="required">Subject<input autoFocus required value={form.subject} onChange={(event) => update("subject", event.target.value)} /></label><label>Goal Type<select value={form.goal_type} onChange={(event) => update("goal_type", event.target.value)}><option value="">Nothing selected</option><option>Sales Target</option><option>Lead Conversion</option><option>Revenue</option><option>Customer Support</option><option>Project Completion</option></select></label><label>Staff Member<select value={form.staff} onChange={(event) => update("staff", event.target.value)}><option value="">All Staff Members</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Achievement<input type="number" min="0" step="0.01" value={form.achievement} onChange={(event) => update("achievement", event.target.value)} /></label><div className="goal-two"><label className="required">Start Date<input required type="date" value={form.start_date} onChange={(event) => update("start_date", event.target.value)} /></label><label>End Date<input type="date" value={form.end_date} onChange={(event) => update("end_date", event.target.value)} /></label></div><label>Description<textarea rows="4" value={form.description} onChange={(event) => update("description", event.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={form.notify_on_achievement} onChange={(event) => update("notify_on_achievement", event.target.checked)} /> Notify all staff members when goal achieved</label><label className="checkbox-label"><input type="checkbox" checked={form.notify_on_failed} onChange={(event) => update("notify_on_failed", event.target.checked)} /> Notify all staff members when goal failed to achieve</label><div className="goal-footer"><button type="button" className="secondary-button" onClick={() => setEditing(false)}>CANCEL</button><button className="primary-button">SAVE</button></div></form></main>;
  return <section className="goals-page"><div className="page-heading"><div><p className="eyebrow">Utilities</p><h1>Goals</h1></div><button className="primary-button" onClick={() => setEditing(true)}>NEW GOAL</button></div>{error && <p className="error-message">{error}</p>}<div className="panel goals-list"><div className="referral-toolbar"><div className="staff-list-controls"><select><option>25</option><option>50</option></select><button className="toolbar-icon-button">EXPORT</button><button className="toolbar-icon-button" onClick={load}>↻</button></div><label className="staff-search">⌕ <input placeholder="Search..." value={search} onChange={(event) => setSearch(event.target.value)} /></label></div><table><thead><tr><th>Subject</th><th>Staff Member</th><th>Achievement</th><th>Start Date</th><th>End Date</th><th>Goal Type</th><th>Progress</th><th /></tr></thead><tbody>{goals.length ? goals.map((goal) => <tr key={goal.id}><td>{goal.subject}<div className="goal-row-actions"><button onClick={() => remove(goal)}>Delete</button></div></td><td>{goal.staff_name || "All Staff Members"}</td><td>{goal.achievement}</td><td>{goal.start_date}</td><td>{goal.end_date || "—"}</td><td>{goal.goal_type}</td><td><div className="goal-progress"><span style={{ width: `${Math.min(Number(goal.progress || 0), 100)}%` }} /></div>{goal.progress}%</td><td /></tr>) : <tr><td colSpan="8" className="goals-empty">No entries found<div className="empty-upload-icon">↥</div></td></tr>}</tbody></table></div></section>;
}
